### ISSUE TITLE
Solidity project.1

### ISSUE THREAD

**Issue by olahamid** [olahamid/Olatundun-Hamid#2]
//STORAGE WORK...E.BOOK
//SPDX-License-Identifier: GPL-3.0

//SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.7;

contract Count {
    //this will get initialised to zero
    uint256 favoriteNumber;
    bool favoriteBool;
    

    struct People {
        uint256 favoriteNumber;
        string name;

    }
    People[] public people;
    function store(uint256 _favoriteNumber) public{
        favoriteNumber =_favoriteNumber;

    }
    // view , pure
    function retrieve() public view returns(uint256) {
        return favoriteNumber;
    function addPerson(string memory _name, uint256 _favoriteNumber) public { 
        people.push(people({favoriteNumber: _favoriteNumber, name:_name}));
    }
}

**Comment by maprob** [comment]
I hopoe you've alreadt fixed it, it's a syntax error people needs to be People, people doesn't exist.

```js
//SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.7;

contract Count {
    //this will get initialised to zero
    uint256 favoriteNumber;
    bool favoriteBool;

    struct People {
        uint256 favoriteNumber;
        string name;
    }

    People[] public people;

    function store(uint256 _favoriteNumber) public{
        favoriteNumber =_favoriteNumber;
    }

    // view , pure
    function retrieve() public view returns(uint256) {
        return favoriteNumber;
    }

    function addPerson(string memory _name, uint256 _favoriteNumber) public { 

        people.push(
            People({
                favoriteNumber: _favoriteNumber,
                name:_name
            })
        );
    }
}
```

**Comment by olahamid** [comment]
Thanks alot man.
